version: 3

tasks:
  build:
    cmds:
      - echo "Building..."
      - cargo build --release

  test:
    cmds:
      - echo "Testing..."
      - cargo test

  lint:
    cmds:
      - echo "Linting..."
      - cargo clippy
      - cargo fmt --all -- --check

  all:
    cmds:
      - task: lint
      - task: test
      - task: build
